/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KsefRouteImport } from './routes/ksef'
import { Route as FaturacaoEletronicaRouteImport } from './routes/faturacao-eletronica'
import { Route as FatturazioneElettronicaRouteImport } from './routes/fatturazione-elettronica'
import { Route as FacturationElectroniqueRouteImport } from './routes/facturation-electronique'
import { Route as ERechnungRouteImport } from './routes/e-rechnung'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaitlistIndexRouteImport } from './routes/waitlist.index'
import { Route as WaitlistPtRouteImport } from './routes/waitlist.pt'
import { Route as WaitlistPlRouteImport } from './routes/waitlist.pl'
import { Route as WaitlistItRouteImport } from './routes/waitlist.it'
import { Route as WaitlistFrRouteImport } from './routes/waitlist.fr'
import { Route as WaitlistDeRouteImport } from './routes/waitlist.de'

const KsefRoute = KsefRouteImport.update({
  id: '/ksef',
  path: '/ksef',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturacaoEletronicaRoute = FaturacaoEletronicaRouteImport.update({
  id: '/faturacao-eletronica',
  path: '/faturacao-eletronica',
  getParentRoute: () => rootRouteImport,
} as any)
const FatturazioneElettronicaRoute = FatturazioneElettronicaRouteImport.update({
  id: '/fatturazione-elettronica',
  path: '/fatturazione-elettronica',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturationElectroniqueRoute = FacturationElectroniqueRouteImport.update({
  id: '/facturation-electronique',
  path: '/facturation-electronique',
  getParentRoute: () => rootRouteImport,
} as any)
const ERechnungRoute = ERechnungRouteImport.update({
  id: '/e-rechnung',
  path: '/e-rechnung',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistIndexRoute = WaitlistIndexRouteImport.update({
  id: '/waitlist/',
  path: '/waitlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistPtRoute = WaitlistPtRouteImport.update({
  id: '/waitlist/pt',
  path: '/waitlist/pt',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistPlRoute = WaitlistPlRouteImport.update({
  id: '/waitlist/pl',
  path: '/waitlist/pl',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistItRoute = WaitlistItRouteImport.update({
  id: '/waitlist/it',
  path: '/waitlist/it',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistFrRoute = WaitlistFrRouteImport.update({
  id: '/waitlist/fr',
  path: '/waitlist/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistDeRoute = WaitlistDeRouteImport.update({
  id: '/waitlist/de',
  path: '/waitlist/de',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e-rechnung': typeof ERechnungRoute
  '/facturation-electronique': typeof FacturationElectroniqueRoute
  '/fatturazione-elettronica': typeof FatturazioneElettronicaRoute
  '/faturacao-eletronica': typeof FaturacaoEletronicaRoute
  '/ksef': typeof KsefRoute
  '/waitlist/de': typeof WaitlistDeRoute
  '/waitlist/fr': typeof WaitlistFrRoute
  '/waitlist/it': typeof WaitlistItRoute
  '/waitlist/pl': typeof WaitlistPlRoute
  '/waitlist/pt': typeof WaitlistPtRoute
  '/waitlist': typeof WaitlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e-rechnung': typeof ERechnungRoute
  '/facturation-electronique': typeof FacturationElectroniqueRoute
  '/fatturazione-elettronica': typeof FatturazioneElettronicaRoute
  '/faturacao-eletronica': typeof FaturacaoEletronicaRoute
  '/ksef': typeof KsefRoute
  '/waitlist/de': typeof WaitlistDeRoute
  '/waitlist/fr': typeof WaitlistFrRoute
  '/waitlist/it': typeof WaitlistItRoute
  '/waitlist/pl': typeof WaitlistPlRoute
  '/waitlist/pt': typeof WaitlistPtRoute
  '/waitlist': typeof WaitlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e-rechnung': typeof ERechnungRoute
  '/facturation-electronique': typeof FacturationElectroniqueRoute
  '/fatturazione-elettronica': typeof FatturazioneElettronicaRoute
  '/faturacao-eletronica': typeof FaturacaoEletronicaRoute
  '/ksef': typeof KsefRoute
  '/waitlist/de': typeof WaitlistDeRoute
  '/waitlist/fr': typeof WaitlistFrRoute
  '/waitlist/it': typeof WaitlistItRoute
  '/waitlist/pl': typeof WaitlistPlRoute
  '/waitlist/pt': typeof WaitlistPtRoute
  '/waitlist/': typeof WaitlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/e-rechnung'
    | '/facturation-electronique'
    | '/fatturazione-elettronica'
    | '/faturacao-eletronica'
    | '/ksef'
    | '/waitlist/de'
    | '/waitlist/fr'
    | '/waitlist/it'
    | '/waitlist/pl'
    | '/waitlist/pt'
    | '/waitlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e-rechnung'
    | '/facturation-electronique'
    | '/fatturazione-elettronica'
    | '/faturacao-eletronica'
    | '/ksef'
    | '/waitlist/de'
    | '/waitlist/fr'
    | '/waitlist/it'
    | '/waitlist/pl'
    | '/waitlist/pt'
    | '/waitlist'
  id:
    | '__root__'
    | '/'
    | '/e-rechnung'
    | '/facturation-electronique'
    | '/fatturazione-elettronica'
    | '/faturacao-eletronica'
    | '/ksef'
    | '/waitlist/de'
    | '/waitlist/fr'
    | '/waitlist/it'
    | '/waitlist/pl'
    | '/waitlist/pt'
    | '/waitlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ERechnungRoute: typeof ERechnungRoute
  FacturationElectroniqueRoute: typeof FacturationElectroniqueRoute
  FatturazioneElettronicaRoute: typeof FatturazioneElettronicaRoute
  FaturacaoEletronicaRoute: typeof FaturacaoEletronicaRoute
  KsefRoute: typeof KsefRoute
  WaitlistDeRoute: typeof WaitlistDeRoute
  WaitlistFrRoute: typeof WaitlistFrRoute
  WaitlistItRoute: typeof WaitlistItRoute
  WaitlistPlRoute: typeof WaitlistPlRoute
  WaitlistPtRoute: typeof WaitlistPtRoute
  WaitlistIndexRoute: typeof WaitlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ksef': {
      id: '/ksef'
      path: '/ksef'
      fullPath: '/ksef'
      preLoaderRoute: typeof KsefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturacao-eletronica': {
      id: '/faturacao-eletronica'
      path: '/faturacao-eletronica'
      fullPath: '/faturacao-eletronica'
      preLoaderRoute: typeof FaturacaoEletronicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatturazione-elettronica': {
      id: '/fatturazione-elettronica'
      path: '/fatturazione-elettronica'
      fullPath: '/fatturazione-elettronica'
      preLoaderRoute: typeof FatturazioneElettronicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturation-electronique': {
      id: '/facturation-electronique'
      path: '/facturation-electronique'
      fullPath: '/facturation-electronique'
      preLoaderRoute: typeof FacturationElectroniqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-rechnung': {
      id: '/e-rechnung'
      path: '/e-rechnung'
      fullPath: '/e-rechnung'
      preLoaderRoute: typeof ERechnungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/': {
      id: '/waitlist/'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/pt': {
      id: '/waitlist/pt'
      path: '/waitlist/pt'
      fullPath: '/waitlist/pt'
      preLoaderRoute: typeof WaitlistPtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/pl': {
      id: '/waitlist/pl'
      path: '/waitlist/pl'
      fullPath: '/waitlist/pl'
      preLoaderRoute: typeof WaitlistPlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/it': {
      id: '/waitlist/it'
      path: '/waitlist/it'
      fullPath: '/waitlist/it'
      preLoaderRoute: typeof WaitlistItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/fr': {
      id: '/waitlist/fr'
      path: '/waitlist/fr'
      fullPath: '/waitlist/fr'
      preLoaderRoute: typeof WaitlistFrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist/de': {
      id: '/waitlist/de'
      path: '/waitlist/de'
      fullPath: '/waitlist/de'
      preLoaderRoute: typeof WaitlistDeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ERechnungRoute: ERechnungRoute,
  FacturationElectroniqueRoute: FacturationElectroniqueRoute,
  FatturazioneElettronicaRoute: FatturazioneElettronicaRoute,
  FaturacaoEletronicaRoute: FaturacaoEletronicaRoute,
  KsefRoute: KsefRoute,
  WaitlistDeRoute: WaitlistDeRoute,
  WaitlistFrRoute: WaitlistFrRoute,
  WaitlistItRoute: WaitlistItRoute,
  WaitlistPlRoute: WaitlistPlRoute,
  WaitlistPtRoute: WaitlistPtRoute,
  WaitlistIndexRoute: WaitlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
